import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased vsc-initialized`}
      >
        <main className="relative">
          <section className="padding-x max-container w-full">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
