import "./globals.css";
import Nav from "@components/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='th'>
      <body
        className={`antialiased vsc-initialized`}
      >
        <main className="relative">
          <Nav />
          <section className="padding-x max-container w-full">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
